<a href="https://colab.research.google.com/github/ddyyaanaaa-ship-it/Diyanatul-Fauziyah-TimDanva-EDA/blob/main/notebooks/P02_praktikum_Diyanatul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

---
## Bagian A — Memuat dan memeriksa data (Latihan 1)
**Tujuan:** sebelum menganalisis apa pun, jawab empat pertanyaan: *berapa besar data ini, apa saja kolomnya, apa tipe datanya, dan seberapa bersih?*

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/EDA/Data/penjualan_umkm_2024.csv')
df.head()

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar
0,TRX2024198,2024-11-14,Jakarta Selatan,Makanan,Sambal Roa,8,38000,5,Transfer,4.7,288800
1,TRX2025061,2024-08-16,Depok,Fashion,Kaos Lokal,8,131500,15,Tunai,3.8,894200
2,TRX2024249,2024-12-21,Depok,Fashion,Hijab Motif,12,102500,10,E-Wallet,4.3,1107000
3,TRX2024903,2024-09-27,Bekasi,Fashion,Kemeja Tenun,11,113500,10,E-Wallet,NaN,1123650
4,TRX2024097,2024-05-06,Depok,Kerajinan,Batik Tulis,8,123000,20,QRIS,4.5,787200

In [ ]:
df.tail()

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar
1207,TRX2025021,2024-11-18,Tangerang Selatan,Makanan,Keripik Singkong,1,22000,20,QRIS,4.1,17600
1208,TRX2024789,2024-09-16,Bogor,Minuman,Teh Herbal,5,55000,10,Transfer,NaN,247500
1209,TRX2024256,2024-08-13,Bogor,Minuman,Sirup Markisa,2,47000,10,QRIS,3.6,84600
1210,TRX2024968,2024-01-08,Bekasi,Kerajinan,Tas Anyaman,7,132000,20,Transfer,4.6,739200
1211,TRX2024952,2024-03-11,Bekasi,Minuman,Teh Herbal,7,29500,20,Transfer,4.4,165200

In [ ]:
df.columns

Index(['id_transaksi', 'tanggal', 'kota', 'kategori', 'produk', 'jumlah',
       'harga_satuan', 'diskon_persen', 'metode_bayar', 'rating_pelanggan',
       'total_bayar'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      1212 non-null   object
 1   tanggal           1212 non-null   object
 2   kota              1212 non-null   object
 3   kategori          1212 non-null   object
 4   produk            1212 non-null   object
 5   jumlah            1212 non-null   int64
 6   harga_satuan      1212 non-null   int64
 7   diskon_persen     1212 non-null   int64
 8   metode_bayar      1187 non-null   object
 9   rating_pelanggan  1151 non-null   float64
 10  total_bayar       1212 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 104.3+ KB

In [ ]:
df.isna().sum()

id_transaksi         0
tanggal              0
kota                 0
kategori             0
produk               0
jumlah               0
harga_satuan         0
diskon_persen        0
metode_bayar        25
rating_pelanggan    61
total_bayar          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(12)

In [ ]:
df['kota'].unique()

array(['Jakarta Selatan', 'Depok', 'Bekasi', 'Tangerang Selatan', 'DEPOK',
       'Bogor', 'BOGOR', 'JAKARTA SELATAN', 'TANGERANG SELATAN', 'BEKASI'],
      dtype=object)

---
## Bagian B — Seleksi dan filter (Latihan 2, berpasangan)
**Tujuan:** mengambil bagian data yang relevan dengan pertanyaan analisis.

In [ ]:
# ----------------------
# B5 a. Ambil transaksi dengan rating_pelanggan < 3
# ----------------------
df_rating_rendah = df[df['rating_pelanggan'] < 3]
print("=== B5a: Transaksi rating < 3 ===")
display(df_rating_rendah)

=== B5a: Transaksi rating < 3 ===

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar
25,TRX2025090,2024-11-27,Tangerang Selatan,Minuman,Sirup Markisa,6,55500,10,QRIS,2.8,299700
148,TRX2024429,2024-06-08,Jakarta Selatan,Fashion,Kaos Lokal,2,100500,0,Tunai,2.9,201000
231,TRX2024955,2024-01-30,Bogor,Makanan,Sambal Roa,12,26000,10,E-Wallet,2.5,280800
244,TRX2024349,2024-10-11,Depok,Minuman,Sirup Markisa,8,44500,0,Transfer,2.8,356000
361,TRX2024423,2024-09-05,Bogor,Minuman,Teh Herbal,12,46000,10,E-Wallet,2.9,496800
368,TRX2024214,2024-05-07,Depok,Minuman,Teh Herbal,4,48500,0,Tunai,2.8,194000
383,TRX2024188,2024-01-22,Depok,Fashion,Hijab Motif,6,118500,0,Tunai,2.9,711000
455,TRX2024886,2024-03-24,Jakarta Selatan,Makanan,Kue Kering,7,26000,5,E-Wallet,2.9,172900
471,TRX2024229,2024-11-03,Depok,Kerajinan,Batik Tulis,6,176000,0,Transfer,2.9,1056000
477,TRX2024751,2024-07-26,Tangerang Selatan,Minuman,Sirup Markisa,11,32500,15,QRIS,2.9,303875
481,TRX2024078,2024-03-11,Jakarta Selatan,Fashion,Hijab Motif,1,93500,0,Transfer,2.8,93500
500,TRX2024362,2024-07-20,Jakarta Selatan,Makanan,Sambal Roa,5,25500,5,Tunai,2.9,121125
718,TRX2024569,2024-05-31,Bogor,Kerajinan,Tas Anyaman,5,177500,0,QRIS,2.9,887500
828,TRX2024166,2024-03-14,Bekasi,Kerajinan,Batik Tulis,4,168000,5,Transfer,2.8,638400
909,TRX2024084,2024-11-17,Bekasi,Minuman,Sirup Markisa,14,45000,5,E-Wallet,2.8,598500
942,TRX2024559,2024-09-14,Jakarta Selatan,Minuman,Sirup Markisa,9,42000,0,QRIS,2.8,378000
1079,TRX2024344,2024-10-01,Depok,Fashion,Hijab Motif,2,91000,15,E-Wallet,2.7,154700
1127,TRX2024120,2024-12-02,Tangerang Selatan,Fashion,Kaos Lokal,3,91000,20,QRIS,2.9,218400
1198,TRX2024337,2024-10-07,Jakarta Selatan,Minuman,Teh Herbal,5,36500,0,QRIS,2.9,182500

In [ ]:
# ----------------------
# B5 b. Jumlah & rata-rata total_bayar
# ----------------------
jumlah_transaksi = len(df_rating_rendah)
rata_rata_bayar = df_rating_rendah['total_bayar'].mean()

print("\n=== B5b ===")
print(f"Jumlah transaksi: {jumlah_transaksi}")
print(f"Rata-rata total_bayar: {rata_rata_bayar:,.2f}")

=== B5b ===
Jumlah transaksi: 19
Rata-rata total_bayar: 386,563.16

In [ ]:
# ----------------------
# B5 c. Kategori 'Kerajinan' ATAU 'Fashion' DAN jumlah >= 10
# ----------------------
df_kategori = df[
    ((df['kategori'] == 'Kerajinan') | (df['kategori'] == 'Fashion')) &
    (df['jumlah'] >= 10)
]
print("\n=== B5c: Kerajinan/Fashion & jumlah >= 10 ===")
display(df_kategori)

=== B5c: Kerajinan/Fashion & jumlah >= 10 ===

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar
2,TRX2024249,2024-12-21,Depok,Fashion,Hijab Motif,12,102500,10,E-Wallet,4.3,1107000
3,TRX2024903,2024-09-27,Bekasi,Fashion,Kemeja Tenun,11,113500,10,E-Wallet,NaN,1123650
36,TRX2024121,2024-05-31,Bekasi,Kerajinan,Batik Tulis,13,132000,5,Tunai,4.4,1630200
39,TRX2024692,2024-08-07,Depok,Kerajinan,Gerabah Hias,10,107000,0,Transfer,4.4,1070000
42,TRX2024232,2024-08-26,Tangerang Selatan,Kerajinan,Tas Anyaman,14,135500,0,QRIS,3.6,1897000
...,...,...,...,...,...,...,...,...,...,...,...
1132,TRX2024076,2024-03-14,Tangerang Selatan,Kerajinan,Gerabah Hias,14,149000,15,QRIS,5.0,1773100
1138,TRX2024503,2024-09-17,Depok,Kerajinan,Tas Anyaman,12,117500,10,QRIS,4.1,1269000
1152,TRX2024036,2024-11-18,Bogor,Kerajinan,Gerabah Hias,12,106000,0,QRIS,5.0,1272000
1177,TRX2024704,2024-07-31,Bekasi,Kerajinan,Gerabah Hias,10,162000,0,QRIS,3.5,1620000
1199,TRX2024398,2024-08-10,Bogor,Kerajinan,Batik Tulis,14,143000,0,QRIS,3.1,2002000

In [ ]:
# B6
hasil = df[
    (df['metode_bayar'] == 'Tunai') &
    (df['total_bayar'] > 500000)
]

hasil[['kota', 'produk', 'jumlah', 'total_bayar']] \
    .sort_values('total_bayar', ascending=False) \
    .head(10)

                 kota        produk  jumlah  total_bayar
385            Bekasi   Batik Tulis      14      2667000
97             Bekasi  Gerabah Hias      12      2286000
742   Jakarta Selatan   Batik Tulis      13      2242500
988             Bogor   Batik Tulis      14      2237200
398   Jakarta Selatan  Kemeja Tenun      14      2093000
129             Bogor   Batik Tulis      13      2054000
116            Bekasi  Gerabah Hias      14      1999200
252             Depok   Hijab Motif      14      1988000
168             Bogor  Gerabah Hias      13      1982500
1000  Jakarta Selatan  Gerabah Hias      11      1947000

---
## Bagian C — Kolom turunan dan pengurutan

In [ ]:
df['harga_bruto'] = df['jumlah'] * df['harga_satuan']
df['hemat'] = df['harga_bruto'] - df['total_bayar']
df[['harga_bruto', 'total_bayar', 'hemat']].head()

   harga_bruto  total_bayar   hemat
0       304000       288800   15200
1      1052000       894200  157800
2      1230000      1107000  123000
3      1248500      1123650  124850
4       984000       787200  196800

In [ ]:
df['tanggal'] = pd.to_datetime(df['tanggal'])
df['bulan'] = df['tanggal'].dt.month
df['nama_hari'] = df['tanggal'].dt.day_name()
df[['tanggal', 'bulan', 'nama_hari']].head()

     tanggal  bulan nama_hari
0 2024-11-14     11  Thursday
1 2024-08-16      8    Friday
2 2024-12-21     12  Saturday
3 2024-09-27      9    Friday
4 2024-05-06      5    Monday

In [ ]:
# C3a
import numpy as np

df['kelas_nilai'] = np.where(
    df['total_bayar'] > 500000,
    'Besar',
    'Kecil'
)

# C3b
df['kelas_nilai'].value_counts()

kelas_nilai
Kecil    845
Besar    367
Name: count, dtype: int64

In [ ]:
# C3c
df[['kota', 'produk', 'total_bayar', 'harga_bruto', 'hemat']] \
    .sort_values('hemat', ascending=False) \
    .head(5)

                  kota        produk  total_bayar  harga_bruto   hemat
295    Jakarta Selatan  Gerabah Hias      2010400      2513000  502600
155    Jakarta Selatan   Batik Tulis      1898400      2373000  474600
220    Jakarta Selatan   Batik Tulis      1898000      2372500  474500
112  Tangerang Selatan  Gerabah Hias      1835600      2294500  458900
381              Bogor  Gerabah Hias      1695200      2119000  423800

---
## Bagian D — Agregasi dengan groupby
Pola yang akan Anda pakai sepanjang semester: **split → apply → combine**.

In [ ]:
# DEMO D1 — agregasi sederhana
df.groupby('kategori')['total_bayar'].mean().round(0)

kategori
Fashion       753346.0
Kerajinan    1043525.0
Makanan       209205.0
Minuman       291653.0
Name: total_bayar, dtype: float64

In [ ]:
# DEMO D2 — beberapa agregasi sekaligus
ringkas = (df.groupby('kategori')
             .agg(jumlah_transaksi=('id_transaksi','count'),
                  total_penjualan=('total_bayar','sum'),
                  rata_rata_nilai=('total_bayar','mean'),
                  rata_rata_rating=('rating_pelanggan','mean'))
             .round(2)
             .sort_values('total_penjualan', ascending=False))
ringkas

,jumlah_transaksi,total_penjualan,rata_rata_nilai,rata_rata_rating
kategori,,,,
Kerajinan,244,254620050,1043524.80,4.14
Fashion,198,149162500,753345.96,4.12
Makanan,477,99790950,209205.35,4.19
Minuman,293,85454225,291652.65,4.13

In [ ]:
# DEMO D3 — dua kunci pengelompokan
df.groupby(['kategori','metode_bayar'])['total_bayar'].sum().unstack(fill_value=0)

metode_bayar  E-Wallet      QRIS  Transfer     Tunai
kategori
Fashion       35309950  39074825  39080725  32852500
Kerajinan     48596275  94013100  50459425  57001000
Makanan       20332425  33687075  21838125  20904100
Minuman       12929075  32409575  23852550  15226000

In [ ]:
# D4a
df.groupby('kota')['total_bayar'] \
    .sum() \
    .sort_values(ascending=False)

kota
Depok                172719800
Jakarta Selatan      133467675
Bogor                105871075
Bekasi                95609225
Tangerang Selatan     65794250
JAKARTA SELATAN        5236300
BEKASI                 4139000
DEPOK                  3962400
BOGOR                  1136250
TANGERANG SELATAN      1091750
Name: total_bayar, dtype: int64

In [ ]:
# D4b
rating_kategori = df.groupby('kategori')['rating_pelanggan'] \
    .mean() \
    .sort_values()

rating_kategori

kategori
Fashion      4.122162
Minuman      4.125455
Kerajinan    4.142553
Makanan      4.185965
Name: rating_pelanggan, dtype: float64

In [ ]:
rating_kategori.head(1)

kategori
Fashion    4.122162
Name: rating_pelanggan, dtype: float64

In [ ]:
# D4c
penjualan_bulan = df.groupby('bulan')['total_bayar'] \
    .sum() \
    .sort_values(ascending=False)

penjualan_bulan

bulan
2     66337075
8     61894850
10    56717775
5     54628625
9     47897550
1     46993050
3     45833275
11    45640975
4     45592425
7     42360050
12    38019650
6     37112425
Name: total_bayar, dtype: int64

In [ ]:
penjualan_bulan.head(1)

bulan
2    66337075
Name: total_bayar, dtype: int64

### Temuan

Berdasarkan hasil analisis, Depok memiliki total penjualan tertinggi sebesar Rp172.719.800. Dari kategori produk, Makanan memiliki rata-rata rating pelanggan tertinggi yaitu 4,19. Sementara itu, berdasarkan bulan, penjualan tertinggi terjadi pada bulan Februari dengan total Rp66.337.075.